import express from "express";
import "dotenv/config.js";
import { connectToDb } from "./dbConnect.js";
import { storeUsersJson } from "./controllers/storeJsonFromUserController.js";
import { sendJson } from "./controllers/sendJsonToUserController.js";
import { errorHandlerIfNotJson } from "./controllers/errorHandler.js";
const { MONGO_SERVER_URL, PORT } = process.env;
await connectToDb(MONGO_SERVER_URL!);
const app = express();
app.use(express.json());
app.post("/*", storeUsersJson);
app.get("/*", sendJson);
app.use(errorHandlerIfNotJson);
app.listen(PORT);
